apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ovirt-csi-sc
parameters:
  # the name of the oVirt storage domain. "nfs" is just an example.
  storageDomainName: "ceph"
  thinProvisioning: "true"
provisioner: csi.ovirt.org
reclaimPolicy: "Delete"
allowVolumeExpansion: true
